name: Update assets-list

on:
  push:
    branches:
      - release # or your default branch name

jobs:
  update assets-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout media-assets repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Update assets_data.js in asset-website repo
        env:
          UPDATE_GITHUB_ACTION_TOKEN: ${{ secrets.UPDATE_GITHUB_ACTION_TOKEN }}
          WEBSITE_REPO: "Veb-Craft/assets-website"
          ASSETS_DATA_FILE_PATH: "src/assets_data.js"
          BASE_URL: "https://media.vebcraft.com"
        run: |
          python .github/scripts/update_assets_data.py
